title: Lana Butorovic # your name (or website title) here
logo: "/images/picture.jpg" # your photo (or logo) here 
description: > # your text below (remove <br> elements if you don't need line breaks)
  Edit these links below   
  <br>
  in _config.yml 
  <br><br>
  <a href="https://www.linkedin.com/in/lana-butorovic/">LinkedIn</a> 
  <br>
  <a href="/pdf/Butorovic%20Lana%20Lehigh%20Resume.pdf">Resume</a>   
  <br>
  <a href="https://github.com/Lana426">GitHub</a>  
  
theme: jekyll-theme-minimal
